# Dataset configuration
dataset:
  train_root: "data/dfdc/train"
  test_root: "data/dfdc/test"
  train_metadata: "data/dfdc/train_metadata.json"
  test_metadata: "data/dfdc/test_metadata.json"
  frame_count: 8
  target_size: [224, 224]
  image_size: [224, 224]
  audio_length: 5.0
  sample_rate: 16000

# Data paths
data:
  train_videos: "data/dfdc/train"
  train_labels: "data/dfdc/train_metadata.json"
  test_videos: "data/dfdc/test"
  test_labels: "data/dfdc/test_metadata.json"
  frame_count: 8
  image_size: [224, 224]
  audio_length: 5.0
  sample_rate: 16000

# Model configuration
model:
  num_classes: 2
  audio_backbone: "facebook/wav2vec2-base-960h"
  visual_backbone: "google/vit-base-patch16-224"
  fusion_dim: 768
  dropout: 0.1

# Training configuration
training:
  batch_size: 16
  num_epochs: 50
  learning_rate: 0.0001
  weight_decay: 0.00001
  num_workers: 4
  output_dir: "outputs/dfdc"
  log_dir: "logs/dfdc"
  checkpoint_dir: "checkpoints/dfdc"
  save_frequency: 1
  mixed_precision: true
  gradient_accumulation_steps: 1
  cudnn_benchmark: true
  cuda_graph: false
  max_grad_norm: 1.0
  early_stopping:
    patience: 20
    min_delta: 0.001
  scheduler:
    T_0: 10
    T_mult: 2
  pin_memory: true
  prefetch_factor: 2
  persistent_workers: true
  log_interval: 1
  validation_interval: 1

# Evaluation configuration
evaluation:
  batch_size: 16
  num_workers: 4
  output_dir: 'results'
  save_predictions: true
  save_visualizations: true
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"
    - "auc"
    - "log_loss" 